// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kljpxxpwwljjjoojojlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsanB4eHB3d2xqampvb2pvamxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2OTA0MDAsImV4cCI6MjA3NTI2NjQwMH0.Z2U-Agk-JhHEtY1Lxq6fZRqHMtd_ZS82DasRlYx12Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});